---
# tasks file for sample-role
- name: パッケージのインストール、アップデート
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ __packeges }}"
__packages:
  - httpd
  - java
  - rsync
- name: .bashrcを配信
  template:
    src: .bashrc.j2
    dest: "/home/hoge/.bashrc"
    owner: root
    group: root
    mode: 0644
