---
# tasks file for sample-role
- name: Install EPEL release for nginx
  yum:
   name: epel-release
   state: present

- name: パッケージのインストール、アップデート
  yum:
    name: "{{ __packages }}"
    state: latest
  tags:
    - packages

- name: Create user
  user:
    name: "webapp"
    comment: "Used to deploy webapp"
    state: present

- name: .bashrcを配信
  template:
    src: .bashrc.j2
    dest: "/home/webapp/.bashrc"
    owner: root
    group: root
    mode: 0644

- name: ファイルの配信
  copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: 0777
